### ISSUE TITLE
Design/Page Elements Checklist

### ISSUE THREAD

**Issue by maranomynet** [piratar/piratar.is#23]
Todolisti fyrir útlitshönnun síðunnar:
- [ ] Header: Become a member
  - The header needs a "Taka þátt", "Ganga í flokkinn" or something similar. See other political party pages for examples.
- [ ] Breadcrumbs
- [ ] Search field
- [ ] Search results
- [ ] Event listi
- [ ] Calendar events
  - The front page should display upcoming event hosted by the Pirate Party. I think a simple list would be the best solution, no need for a complicated calendar like view.  
    The question is more how we would input the event into WordPress. If they should be hosted on Facebook and imported from there or if Pirate Party site should be the primary place to store the events. I think using Facebook would be the best solution since event need to be created there anyway.
- [ ] Event page (See #20) 
- [ ] Navigation
  - Each page has to have a description
  - Landing pages should display a list/grid of child pages if any.
  - The site has two navigation lists. The main nav and then the burger menu that should include the full  site tree.
- [ ] Footer
- [x] Homepage: Pictures, lots of pictures!
  - A large section with Instagram photos and a large Facebook Like-box with the profile pictures of people who like the PP on FB.
- [ ] Homepage: Acitve elections/issues from Wasa2il
  - A section that shows the last X open votes and/or open elections from the Wasa2il system. Should also include a link to the front page of x.piratar.is
- [ ] "Election mode" promotion banner
  - In elections, we need a feature that displays a banner on the front page with a CTA button to the election landing page, depending on if its a local or parliamentary elections.
- [ ] People
  - List of people that work for or represent the party.
  - Should include contact information, name and position as a category.
  - Can be used on the group and member pages as well as on the Píratar á Þingi page.
- [ ] Template: News
- [ ] Template: Participate/Pirateparty
  - A page that outlines all they ways you can join and/or help the party. 
    - How to participate/FAQ
    - Learn how pirates work and collaborate
    - Donate
    - Join as member
    - Working groups (málefnastarf)
    - Pirate school / Learn to be a pirate
    - Public events
  - See site map for more details.
- [ ] Template/Page: Groups and member associations (See: #9)
- [ ] Template: Píratar á Alþingi
  - A page for Pirates at Alþingi including list of parliamentary bills, proposals and inquiries. A list of our parliamentarians linking to their individual profile pages.
  - Nice to have: Make custom fields/post types for inquiries. See "Fyrirspurnir frá þingflokki" page.
- [ ] Homepage: Newsfeed
  - Display news and blog posts in one unified feed with the possibility of displaying one or more items pinned to the top.
- [ ] Template: Page and single post
- [ ] Homepage: Word definitions
  - Word definition section that will look to explain common words from the Pirate Party base policy and other words from the Pirate Party universe. A list of words and its definition. On the front page we could display one at a time selected by random.
- [ ] Homepage: How to participage
  - A section that helps users to quickly find how they can participate in the party, sign up as a member, join policy groups and so on. The current web site has something similar.

**Comment by maranomynet** [comment]
Ég henti upp þessum lista og loka í leiðinni fullt af "minnispunkta" issues.
